### ISSUE TITLE
Unable to build on latest Debian

### ISSUE THREAD

**Issue by linux019** [yuezk/GlobalProtect-openconnect#251] opened 2023-08-08 14:52 UTC
./scripts/verify-debian-package.sh 
```
dpkg-buildpackage: info: source package globalprotect-openconnect
dpkg-buildpackage: info: source version 1.4.9-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Kevin Yue <k3vinyue@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean
   dh_auto_clean
	make -j8 clean
make[1]: Entering directory '/tmp/GlobalProtect-openconnect'
make[2]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Entering directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[3]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[2]: Leaving directory '/tmp/GlobalProtect-openconnect'
make[1]: Leaving directory '/tmp/GlobalProtect-openconnect'
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f -- debian/globalprotect-openconnect.substvars debian/files
	rm -fr -- debian/globalprotect-openconnect/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source -b .
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 255
```

Solution:
Replace all strings "1.4.9-1" with "1.4.9" in "debian/changelog"

**Comment by martindorey** [comment] 2023-12-29 17:13
Dupe of https://github.com/yuezk/GlobalProtect-openconnect/issues/184

**Closed** 2024-03-10 09:55 UTC
