### ISSUE TITLE
'Error: Invalid auth cookie, retrying can help' with beta2

### ISSUE THREAD

**Issue by rmontanana** [yuezk/GlobalProtect-openconnect#285] opened 2024-01-18 21:13 UTC
Tried beta 2 and still got the same message, I've tried to change the client to windows (I've got Fedora 39), to Linux but nothing seems to work anyway. I've cleared the credentials to start from scratch with beta 2 but didn't have any luck with this.

I had working prior version but updated automatically to this beta and stopped working since then.

Thanks for your attention

**Comment by sh4t7er** [comment] 2024-01-19 04:26
Same thing here. I am getting the following error when trying to connect after updating. Error: Invalid auth cookie, retrying can help

**Comment by dchorazkiewicz** [comment] 2024-01-19 05:34
Same thing here!

**Comment by ryanjkthedev** [comment] 2024-01-19 10:21
This is an issue for me also (and several users I support). Was working fine until the recent changes.

**Comment by rmontanana** [comment] 2024-01-19 11:45
I would thank if anybody have fedora39 1.49 binary, I've tried to build myself but got this error
```
[ 63%] Linking CXX executable gpclient
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QWindow::setVulkanInstance(QVulkanInstance*)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::setLayers(QList<QByteArray> const&)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QTextureGlyphCache::populate(QFontEngine*, int, unsigned int const*, QFixedPoint const*, bool)@Qt_5_PRIVATE_API'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QWindow::vulkanInstance() const@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::QVulkanInstance()@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::setExtensions(QList<QByteArray> const&)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::create()@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::~QVulkanInstance()@Qt_5'
collect2: error: ld returned 1 exit status
gmake[2]: *** [GPClient/CMakeFiles/gpclient.dir/build.make:476: GPClient/gpclient] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:353: GPClient/CMakeFiles/gpclient.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by aallu-rythmos** [comment] 2024-01-19 14:24
https://github.com/yuezk/GlobalProtect-openconnect/issues/280#issuecomment-1897922829

For `ubuntu 22`, this solution should be a quick workaround until we get a new version that fixes the issue.

**Comment by aallu-rythmos** [comment] 2024-01-19 19:57
> @aallu-rythmos I tried building that version as well as a few other 1.x versions, and they are broken on fedora. Auth seems to succeed, but the window doesn't close and a connection is never established.

For `Fedora` unfortunately I can be of no or very little help. sorry. The UI freeze issue must be due to dependency libraries (python) or some other dependency OS packages that are causing the issue, I too faced the issue with some versions, but `1.49` was stable for me.

**Comment by cmslay18** [comment] 2024-01-20 17:12
@lbhdc I successfully built it just now on fedora 39 and I no longer have the issue's you were having! I did also attempt to change operating system types on the new beta, as well as the SSL settings to no dice. I saw that there was a fix pushed for a similar issue, but the update didn't do me any good unfortunately. Downgrading fixed all my issues though.  Do make sure to uninstall globalprotect-openconnect before installing the source tar. My order of operations were the following:

1. ` wget https://github.com/yuezk/GlobalProtect-openconnect/releases/download/v1.4.9/globalprotect-openconnect-1.4.9.tar.gz`
2. `sudo dnf remove globalprotect-openconnect`
3. `sudo dnf install cmake qtkeychain-qt5-devel qt5-qtbase-devel qt5-qtbase-devel qt5-qtwebsockets-devel qt5-qtwebengine-devel`
4. `tar -xvf globalprotect-openconnect-1.4.9.tar.gz`
5. `cd globalprotect-openconnect-1.4.9`
6. ./scripts/install-fedora.sh

The ubuntu fix threw the source tar in opt which is probably the best place to put it. Just make sure the owner and permissions of the extracted tarball directory are good when you run the script! also make sure to run the install-fedora script from inside the extracted tarballs top directory. the other helper scripts seem to be invoked based on the relative path, and that relative path assumes you are in the ../globalprotect-openconnect-1.4.9 directory. I am also running a wayland session! Not sure if that matters. But the GUI is fully functional for me, and a connection is established. I might have extra packages installed that you are missing. If need be I can throw my packagelist as a text file for you to diff against.

**Comment by zaikunzhang** [comment] 2024-01-21 02:16
Same here. Is degrading to 1.4.9 the only solution? Will a feature release solve the problem? Thanks.

**Comment by hjelmeland** [comment] 2024-01-21 10:09
+1

**Comment by zaikunzhang** [comment] 2024-01-21 18:25
Same behavior with [2.0-beta4](https://github.com/yuezk/GlobalProtect-openconnect/releases/tag/v2.0.0-beta4).

**Comment by sh4t7er** [comment] 2024-01-21 23:05
Same thing here (Error: Invalid auth cookie, retrying can help) with https://github.com/yuezk/GlobalProtect-openconnect/releases/tag/v2.0.0-beta4.

**Comment by maudechai** [comment] 2024-01-21 23:40
I'm experiencing the same auth cookie error. Ubuntu 22.04.3LTS with v2.0.0-beta4.

**Comment by userofryzen** [comment] 2024-01-22 07:11
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/33232977/0f48e8d1-97f1-4f24-9f39-b709d57a6c44)
there are errors yet.

**Comment by ap91484** [comment] 2024-01-22 10:45
I'm experiencing the same auth cookie error. 
This is the only software that worked reliably on linux for GlobalConnect connections. I subscribed for the yearly payment and gladly support the author. Right now I downgraded to 1.4.9.
@yuezk : Is it possible for the subscribed users to get an email, when this error is fixed? Thanks for your work!

**Comment by yuezk** [comment] 2024-01-22 11:01
@ap91484 Thanks for your support, I’m willing to help you, but I couldn’t reproduce this problem with my portal. It would be helpful if you could provide a test account for reproducing this. I don’t know if this is feasible for your case.

Feel free to contact me at k3vinyue@gmail.com

**Comment by cmslay18** [comment] 2024-01-22 17:20
It is probably best to stay on 1.X until it is out of beta. Also love what the repo does, as the official GUI client for Linux is a mess and I have supported the developer as well. Great project all around! The newest release (beta 5) still produces the same errors on all PA's that are in use for me. Not sure what is going on? In my free time, I can try and look at the code/ pop out wireshark since it seems to be in the auth handshake. This occurs for both SAML and not SAML connections. I didn't know if it had to do with upgrading from the 1.X package to the new 2.X package, but on a clean install (inside a VM) the error persists.

**Comment by sh4t7er** [comment] 2024-01-22 18:06
Still getting "Error: Invalid auth cookie, retrying can help" with 2.0.0-beta5. I also get the same error when using the new Default Browser option.

**Comment by sh4t7er** [comment] 2024-01-23 21:00
I can confirm. This issue is now resolved for me with 2.0.0-beta7.

**Comment by yuezk** [comment] 2024-01-24 01:06
> I can confirm. This issue is now resolved for me with 2.0.0-beta7.

Thanks for the confirmation. Closing.

**Closed by yuezk** 2024-01-24 01:06 UTC

**Comment by ap91484** [comment] 2024-01-24 05:03
2.0.0-beta7 is working for me also. It even remembered the authentication after reinstalling!

**Comment by zaikunzhang** [comment] 2024-01-25 07:21
2.0.0-beta7 is working on my side. Thank you very much @yuezk !

A side note: In Settings/Connection, I have to choose "Windows", even though I am running Ubuntu 22.04. Is this expected?

**Comment by yuezk** [comment] 2024-01-25 07:36
> A side note: In Settings/Connection, I have to choose "Windows", even though I am running Ubuntu 22.04. Is this expected?

Yes. It is expected. It's more related to the portal server, experiences teach us that configuring it as Windows or macOS could get around this. That's why I added them as options.
