### ISSUE TITLE
Unknown response for gateway prelogin interface.

### ISSUE THREAD

**Issue by gumbarros** [yuezk/GlobalProtect-openconnect#211] opened 2023-01-31 16:47 UTC
![image](https://user-images.githubusercontent.com/52143624/215827845-2f86e6b3-b8dd-44e7-99e8-c8d02b367670.png)
Pop!_OS 22.04 LTS

**Comment by yuezk** [comment] 2023-02-02 06:28
Did it work before? And please provide the logs by running the `gpclient` in the Terminal and collecting the logs.

**Comment by stressedtux** [comment] 2023-02-08 17:10
Im getting the same error, im also using the latest version but debian 11. 

it seams that for some reason the host of the gateway changes for "ssl-vpn" and i get a "Host not found" error, not sure if is normal behavior (im using ms ad saml)

![vpn-gp](https://user-images.githubusercontent.com/36582356/217601154-7675184c-5e37-4a95-949d-cbcd3fcc5a98.png)

**Comment by evanhorn** [comment] 2023-02-26 18:10
I believe that I have the same issue on Ubuntu 20.04 with Gnome 3.36.8. When I start my system, I can connect without any problem. However, if I remain connected long enough, i.e., on the order of several hours, I will eventually lose my connection. When I attempt to reconnect, I am not asked for my credentials, and I get the same messages as the OP (see log below). I have tried to “Reset”, but even then, I am not asked for my credentials and I get the same behavior.

When this occurs, I have manually stopped the process, restarted NetworkManager, and logged out and back in, all to no avail. The only thing I have found that corrects the issue is rebooting my laptop. 

I have noticed another peculiarity. After a failed connection, I can ping, say 8.8.8.8, and ping starts and runs promptly. However, if I ping, say google.com, nothing happens for maybe a minute, then I get `PING google.com (142.251.45.238) 56(84) bytes of data.`, then another minute, and ping starts running with reasonable ping times (on the order of ms). This only seems to occur after failing to connect; otherwise, ping starts and immediately starts pinging.

```
2023-02-23 13:10:55.645 INFO  [978287] [main@24] GlobalProtect started, version: 1.4.9
2023-02-23 13:10:56.029 INFO  [978287] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-02-23 13:10:58.820 INFO  [978287] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-02-23 13:10:58.999 INFO  [978287] [GPClient::doConnect@238] Start connecting...
2023-02-23 13:10:59.000 INFO  [978287] [GPClient::doConnect@254] Start gateway login using the previously saved gateway...
2023-02-23 13:10:59.000 INFO  [978287] [GPClient::gatewayLogin@361] Performing gateway login...
2023-02-23 13:10:59.004 INFO  [978287] [GatewayAuthenticator::authenticate@28] Start gateway authentication...
2023-02-23 13:10:59.005 INFO  [978287] [GatewayAuthenticator::login@41] Trying to login the gateway at https://auvpn2.auburn.edu/ssl-vpn/login.esp, with prot=https%3A&server=&jnlpReady=jnlpReady&computer=evanhorn-laptop&ok=Login&direct=yes&clientVer=4100&clientos=Ubuntu 20.04&os-version=Ubuntu 20.04.5 LTS&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
2023-02-23 13:11:41.934 ERROR [978287] [GatewayAuthenticator::onLoginFinished@53] Failed to login the gateway at https://auvpn2.auburn.edu/ssl-vpn/login.esp, Host auvpn2.auburn.edu not found
2023-02-23 13:11:41.940 INFO  [978287] [GatewayAuthenticator::doAuth@81] Perform the gateway prelogin at https://auvpn2.auburn.edu/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04
2023-02-23 13:12:37.997 ERROR [978287] [GatewayAuthenticator::onPreloginFinished@92] Failed to prelogin the gateway at https://auvpn2.auburn.edu/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04, Host auvpn2.auburn.edu not found
2023-02-23 13:12:37.997 INFO  [978287] [GPClient::onGatewayFail@402] Quick connection failed, trying to portal login...
2023-02-23 13:12:38.002 INFO  [978287] [PortalAuthenticator::authenticate@35] (1/5) attempts, preform portal prelogin at https://auvpn2.auburn.edu/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04
2023-02-23 13:13:22.046 ERROR [978287] [PortalAuthenticator::onPreloginFinished@46] Error occurred while accessing https://auvpn2.auburn.edu/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04, Host auvpn2.auburn.edu not found
2023-02-23 13:13:22.046 INFO  [978287] [GPClient::onPortalPreloginFail@321] Portal prelogin failed, treat the portal address as a gateway.Error occurred on the portal prelogin interface.
2023-02-23 13:13:22.046 INFO  [978287] [GPClient::tryGatewayLogin@342] Try to preform login on the the gateway interface...
2023-02-23 13:13:22.046 INFO  [978287] [GPClient::setAllGateways@455] Updating all the gateways...
2023-02-23 13:13:22.046 INFO  [978287] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-02-23 13:13:22.047 INFO  [978287] [GPClient::setCurrentGateway@475] Updating the current gateway to auvpn2.auburn.edu
2023-02-23 13:13:22.047 INFO  [978287] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-02-23 13:13:22.048 INFO  [978287] [GPClient::gatewayLogin@361] Performing gateway login...
2023-02-23 13:13:22.053 INFO  [978287] [GatewayAuthenticator::authenticate@28] Start gateway authentication...
2023-02-23 13:13:22.053 INFO  [978287] [GatewayAuthenticator::login@41] Trying to login the gateway at https://auvpn2.auburn.edu/ssl-vpn/login.esp, with prot=https%3A&server=&jnlpReady=jnlpReady&computer=evanhorn-laptop&ok=Login&direct=yes&clientVer=4100&clientos=Ubuntu 20.04&os-version=Ubuntu 20.04.5 LTS&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
2023-02-23 13:14:10.460 ERROR [978287] [GatewayAuthenticator::onLoginFinished@53] Failed to login the gateway at https://auvpn2.auburn.edu/ssl-vpn/login.esp, Host auvpn2.auburn.edu not found
2023-02-23 13:14:10.467 INFO  [978287] [GatewayAuthenticator::doAuth@81] Perform the gateway prelogin at https://auvpn2.auburn.edu/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04
2023-02-23 13:14:59.433 ERROR [978287] [GatewayAuthenticator::onPreloginFinished@92] Failed to prelogin the gateway at https://auvpn2.auburn.edu/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Ubuntu 20.04, Host auvpn2.auburn.edu not found
```

**Comment by evanhorn** [comment] 2023-03-29 12:20
I have recently upgraded to Ubuntu 22.04 and this problem appears to be resolved for me. I still occasionally get drop-outs (and occasionally forget to disconnect prior to suspending), but in all cases (so far—knock on wood), I have been asked for my credentials and able to reconnect without issue.

**Comment by gumbarros** [comment] 2023-03-29 14:14
@evanhorn  did you **downgrade** or **update**? I'm on Ubuntu 22.10 and not working 😥

**Comment by evanhorn** [comment] 2023-03-29 14:22
I upgraded — I originally commented on my problems using 20.04.

I realized that you were using 22.10, and I was not trying to imply that my issue was related to a specific version; however, I did want to communicate that for me, the issues disappeared upon upgrading to 22.04.

**Comment by denwbd** [comment] 2023-08-04 17:31
Hello @yuezk, having the similar issue here:

```
2023-08-04 20:12:09.777 INFO  [483204] [GPClient::doConnect@238] Start connecting...
2023-08-04 20:12:09.777 INFO  [483204] [GPClient::doConnect@254] Start gateway login using the previously saved gateway...
2023-08-04 20:12:09.777 INFO  [483204] [GPClient::gatewayLogin@361] Performing gateway login...
2023-08-04 20:12:09.781 INFO  [483204] [GatewayAuthenticator::authenticate@28] Start gateway authentication...
2023-08-04 20:12:09.781 INFO  [483204] [GatewayAuthenticator::login@41] Trying to login the gateway at https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp, with prot=https%3A&server=&jnlpReady=jnlpReady&computer=owl&ok=Login&direct=yes&clientVer=4100&clientos=Linux&os-version=Ubuntu 22.04.2 LTS&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
2023-08-04 20:12:10.122 ERROR [483204] [GatewayAuthenticator::onLoginFinished@53] Failed to login the gateway at https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp, Error transferring https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp - server replied: status code 512
2023-08-04 20:12:10.122 INFO  [483204] [GatewayAuthenticator::doAuth@81] Perform the gateway prelogin at https://<<censored>>.<<censored>>.com/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
2023-08-04 20:12:10.222 INFO  [483204] [GatewayAuthenticator::onPreloginFinished@98] Gateway prelogin succeeded.
2023-08-04 20:12:10.222 INFO  [483204] [PreloginResponse::parse@26] Start parsing the prelogin response...
2023-08-04 20:12:10.222 ERROR [483204] [GatewayAuthenticator::onPreloginFinished@107] Unknown prelogin response for https://<<censored>>.<<censored>>.com/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, got <?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Error</status>
<ccusername></ccusername>
<autosubmit></autosubmit>
<msg>GlobalProtect gateway does not exist</msg>
<newmsg></newmsg>
<license></license>
<authentication-message></authentication-message>
<username-label></username-label>
<password-label></password-label>
<panos-version>1</panos-version>
<saml-default-browser>yes</saml-default-browser>
<krb-norm-username></krb-norm-username>
<krb-auth-status>0</krb-auth-status>
<cas-auth></cas-auth>
<saml-auth-status>0</saml-auth-status>
<saml-auth-method></saml-auth-method>
<saml-request-timeout></saml-request-timeout>
<saml-request-id></saml-request-id>
<saml-request></saml-request>
<auth-api>no</auth-api><region></region>
</prelogin-response>
2023-08-04 20:12:10.222 INFO  [483204] [GPClient::onGatewayFail@402] Quick connection failed, trying to portal login...
2023-08-04 20:12:10.231 INFO  [483204] [PortalAuthenticator::authenticate@35] (1/5) attempts, preform portal prelogin at https://<<censored>>.<<censored>>.com/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
2023-08-04 20:12:10.330 INFO  [483204] [PortalAuthenticator::onPreloginFinished@52] Portal prelogin succeeded.
2023-08-04 20:12:10.330 INFO  [483204] [PreloginResponse::parse@26] Start parsing the prelogin response...
2023-08-04 20:12:10.330 INFO  [483204] [PortalAuthenticator::onPreloginFinished@56] Finished parsing the prelogin response. The region field is: UA
2023-08-04 20:12:10.330 INFO  [483204] [PortalAuthenticator::samlAuth@119] Trying to perform SAML login with saml-method POST
2023-08-04 20:12:10.367 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from data:text/html;charset=UTF-8,<<censored>>
2023-08-04 20:12:10.367 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:11.208 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://sso.<<censored>>.com/app/palo_alto_networks_prisma_access/<<censored>>/sso/saml
2023-08-04 20:12:11.208 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:11.428 INFO  [483204] [SAMLLoginWindow::onLoadFinished@109] Load finished https://sso.<<censored>>.com/app/palo_alto_networks_prisma_access/<<censored>>/sso/saml
2023-08-04 20:12:11.493 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://login.okta.com/<<censored>>/iframe.html
2023-08-04 20:12:11.493 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:19.921 INFO  [483204] [SAMLLoginWindow::SAMLLoginWindow@31] MAX_WAIT_TIME exceeded, display the login window.
2023-08-04 20:12:21.750 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://sso.<<censored>>.com/auth/services/devicefingerprint
2023-08-04 20:12:21.750 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:24.668 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://sso.<<censored>>.com/login/sessionCookieRedirect
2023-08-04 20:12:24.668 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:24.767 INFO  [483204] [SAMLLoginWindow::onLoadFinished@109] Load finished https://sso.<<censored>>.com/login/sessionCookieRedirect
2023-08-04 20:12:24.775 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://login.okta.com/<<censored>>/iframe.html
2023-08-04 20:12:24.775 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:32.565 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://sso.<<censored>>.com/login/sessionCookieRedirect
2023-08-04 20:12:32.565 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:32.615 INFO  [483204] [SAMLLoginWindow::onLoadFinished@109] Load finished https://sso.<<censored>>.com/login/sessionCookieRedirect
2023-08-04 20:12:33.042 INFO  [483204] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://<<censored>>.<<censored>>.com/SAML20/SP/ACS
2023-08-04 20:12:33.043 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:33.059 INFO  [483204] [SAMLLoginWindow::onLoadFinished@109] Load finished https://<<censored>>.<<censored>>.com/SAML20/SP/ACS
2023-08-04 20:12:33.060 INFO  [483204] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-08-04 20:12:33.060 INFO  [483204] [SAMLLoginWindow::checkSamlResult@97] Got the SAML authentication information successfully. username: <<censored>>, preloginCookie: ct9Q2nG5Ls4dC2LD71Pn2G/NRqCfo0/fb4L/rCyzzUUlRxsoThsITHSjGzulonHQKfyMGw==, userAuthCookie: 
2023-08-04 20:12:33.060 INFO  [483204] [PortalAuthenticator::onSAMLLoginSuccess@142] SAML login succeeded, got the prelogin-cookie
2023-08-04 20:12:33.060 INFO  [483204] [PortalAuthenticator::fetchConfig@173] Fetching the portal config from https://<<censored>>.<<censored>>.com/global-protect/getconfig.esp
2023-08-04 20:12:33.082 ERROR [483204] [CDPCommandManager::onSocketError@86] WebSocket error1
2023-08-04 20:12:33.082 INFO  [483204] [CDPCommandManager::onSocketDisconnected@81] WebSocket disconnected
2023-08-04 20:12:33.315 INFO  [483204] [PortalAuthenticator::onFetchConfigFinished@199] Fetch the portal config succeeded.
2023-08-04 20:12:33.316 INFO  [483204] [PortalConfigResponse::parse@20] Start parsing the portal configuration...
2023-08-04 20:12:33.316 INFO  [483204] [PortalConfigResponse::parse@32] Start reading portal-userauthcookie
2023-08-04 20:12:33.316 INFO  [483204] [PortalConfigResponse::parse@35] Start reading portal-prelogonuserauthcookie
2023-08-04 20:12:33.316 INFO  [483204] [PortalConfigResponse::parse@42] Finished parsing portal configuration.
2023-08-04 20:12:33.316 INFO  [483204] [GPClient::onPortalSuccess@302] Portal authentication succeeded.
2023-08-04 20:12:33.316 INFO  [483204] [GPClient::onPortalSuccess@306] No gateway found in portal configuration, treat the portal address as a gateway.
2023-08-04 20:12:33.316 INFO  [483204] [GPClient::tryGatewayLogin@342] Try to preform login on the the gateway interface...
2023-08-04 20:12:33.316 INFO  [483204] [GPClient::setAllGateways@455] Updating all the gateways...
2023-08-04 20:12:33.316 INFO  [483204] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-08-04 20:12:33.318 INFO  [483204] [GPClient::setCurrentGateway@475] Updating the current gateway to <<censored>>.<<censored>>.com
2023-08-04 20:12:33.318 INFO  [483204] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-08-04 20:12:33.320 INFO  [483204] [GPClient::gatewayLogin@361] Performing gateway login...
2023-08-04 20:12:33.327 INFO  [483204] [GatewayAuthenticator::authenticate@28] Start gateway authentication...
2023-08-04 20:12:33.327 INFO  [483204] [GatewayAuthenticator::login@41] Trying to login the gateway at https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp, with prot=https%3A&server=&jnlpReady=jnlpReady&computer=owl&ok=Login&direct=yes&clientVer=4100&clientos=Linux&os-version=Ubuntu 22.04.2 LTS&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
2023-08-04 20:12:33.582 ERROR [483204] [GatewayAuthenticator::onLoginFinished@53] Failed to login the gateway at https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp, Error transferring https://<<censored>>.<<censored>>.com/ssl-vpn/login.esp - server replied: status code 512
2023-08-04 20:12:33.582 INFO  [483204] [GatewayAuthenticator::doAuth@81] Perform the gateway prelogin at https://<<censored>>.<<censored>>.com/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
2023-08-04 20:12:33.681 INFO  [483204] [GatewayAuthenticator::onPreloginFinished@98] Gateway prelogin succeeded.
2023-08-04 20:12:33.681 INFO  [483204] [PreloginResponse::parse@26] Start parsing the prelogin response...
2023-08-04 20:12:33.681 ERROR [483204] [GatewayAuthenticator::onPreloginFinished@107] Unknown prelogin response for https://<<censored>>.<<censored>>.com/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, got <?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Error</status>
<ccusername></ccusername>
<autosubmit></autosubmit>
<msg>GlobalProtect gateway does not exist</msg>
<newmsg></newmsg>
<license></license>
<authentication-message></authentication-message>
<username-label></username-label>
<password-label></password-label>
<panos-version>1</panos-version>
<saml-default-browser>yes</saml-default-browser>
<krb-norm-username></krb-norm-username>
<krb-auth-status>0</krb-auth-status>
<cas-auth></cas-auth>
<saml-auth-status>0</saml-auth-status>
<saml-auth-method></saml-auth-method>
<saml-request-timeout></saml-request-timeout>
<saml-request-id></saml-request-id>
<saml-request></saml-request>
<auth-api>no</auth-api><region></region>
</prelogin-response>
```

**Comment by yuezk** [comment] 2023-08-07 06:41
Hi @denwbd you could try the new client on the `refactor` branch to see if it still happens.

**Comment by yuezk** [comment] 2024-03-23 13:05
Closing it for now, reopen it if it still exits in 2.x.

**Closed by yuezk** 2024-03-23 13:05 UTC
