### ISSUE TITLE
WebSocket error1

### ISSUE THREAD

**Issue by risostk** [yuezk/GlobalProtect-openconnect#236] opened 2023-05-17 22:06 UTC
Hi, I got the 'WebSocket error1' error after login. It goes back to the start window and shows 'Not Connected.' Any idea of what goes wrong? Thanks!
OS: Fedora 37
openconnect: 9.01
gpclient: 1.4.9

Here is the log:
```
$ gpclient 
2023-05-17 16:17:25.092 INFO  [59437] [main@24] GlobalProtect started, version: 1.4.9
QSocketNotifier: Can only be used with threads started with QThread
2023-05-17 16:17:25.260 INFO  [59437] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2023-05-17 16:17:28.250 INFO  [59437] [GPClient::populateGatewayMenu@133] Populating the Switch Gateway menu...
2023-05-17 16:17:28.352 INFO  [59437] [GPClient::doConnect@238] Start connecting...
2023-05-17 16:17:28.352 INFO  [59437] [GPClient::doConnect@254] Start gateway login using the previously saved gateway...
2023-05-17 16:17:28.352 INFO  [59437] [GPClient::gatewayLogin@361] Performing gateway login...
2023-05-17 16:17:28.361 INFO  [59437] [GatewayAuthenticator::authenticate@28] Start gateway authentication...
2023-05-17 16:17:28.361 INFO  [59437] [GatewayAuthenticator::login@41] Trying to login the gateway at xxx
2023-05-17 16:17:28.884 ERROR [59437] [GatewayAuthenticator::onLoginFinished@53] Failed to login the gateway at xxx
2023-05-17 16:17:28.932 INFO  [59437] [GatewayAuthenticator::onPreloginFinished@98] Gateway prelogin succeeded.
2023-05-17 16:17:28.932 INFO  [59437] [PreloginResponse::parse@26] Start parsing the prelogin response...
2023-05-17 16:17:28.932 INFO  [59437] [GatewayAuthenticator::samlAuth@152] Trying to perform SAML login with saml-method REDIRECT

DevTools listening on ws://127.0.0.1:12315/devtools/browser/58d16444-e045-4119-8f7d-67dd51ba5f2e
2023-05-17 16:17:29.070 INFO  [59437] [SAMLLoginWindow::login@49] Redirect to xxx
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:12315
2023-05-17 16:17:29.779 INFO  [59437] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from xxx
2023-05-17 16:17:29.779 INFO  [59437] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-05-17 16:17:29.894 INFO  [59437] [SAMLLoginWindow::onLoadFinished@109] Load finished xxx
2023-05-17 16:17:39.459 INFO  [59437] [SAMLLoginWindow::SAMLLoginWindow@31] MAX_WAIT_TIME exceeded, display the login window.
2023-05-17 16:18:13.892 INFO  [59437] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from xxx
2023-05-17 16:18:13.892 INFO  [59437] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-05-17 16:18:13.922 INFO  [59437] [SAMLLoginWindow::onLoadFinished@109] Load finished xxx
2023-05-17 16:18:14.929 INFO  [59437] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from xxx
2023-05-17 16:18:14.929 INFO  [59437] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-05-17 16:18:14.990 INFO  [59437] [SAMLLoginWindow::onLoadFinished@109] Load finished https://api-906cc653.duosecurity.com/xxx
js: Refused to load the image 'https://duo.com/' because it violates the following Content Security Policy directive: "img-src 'self'  ".

2023-05-17 16:18:15.828 INFO  [59437] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://fed.it.company.com/idp/profile/SAML2/Redirect/SSO?execution=e1s2&_eventId_proceed=1
2023-05-17 16:18:15.828 INFO  [59437] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-05-17 16:18:15.835 INFO  [59437] [SAMLLoginWindow::onLoadFinished@109] Load finished https://fed.it.company.com/idp/profile/SAML2/Redirect/SSO?execution=e1s2&_eventId_proceed=1
2023-05-17 16:18:15.974 INFO  [59437] [SAMLLoginWindow::onResponseReceived@69] Trying to receive authentication cookie from https://vpn.company.com/SAML20/SP/ACS
2023-05-17 16:18:15.974 INFO  [59437] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-05-17 16:18:15.974 INFO  [59437] [SAMLLoginWindow::checkSamlResult@97] Got the SAML authentication information successfully. username: user@company.com, preloginCookie: uSaN7Nug1m28KZAa7ixgjWiAfrrlNNhEHTIwP+wvH7WKcvQ7FLdicQiRmocjOqIR, userAuthCookie: 
2023-05-17 16:18:15.974 INFO  [59437] [GatewayAuthenticator::onSAMLLoginSuccess@175] SAML login succeeded, got the prelogin-cookie xxx
2023-05-17 16:18:15.975 INFO  [59437] [GatewayAuthenticator::login@41] Trying to login the gateway at https://vpn.company.com/ssl-vpn/login.esp, with xxx
2023-05-17 16:18:16.009 ERROR [59437] [CDPCommandManager::onSocketError@86] WebSocket error1
2023-05-17 16:18:16.009 INFO  [59437] [CDPCommandManager::onSocketDisconnected@81] WebSocket disconnected
2023-05-17 16:18:16.382 INFO  [59437] [gpclient::helper::parseGatewayResponse@57] Start parsing the gateway response...
2023-05-17 16:18:16.382 INFO  [59437] [gpclient::helper::parseGatewayResponse@58] The gateway response is: <?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>d070a412cd2197311832ad6278602e0c</argument><argument>ee7bfb21ccc611069e5ef2fe66536a9f04458c2b</argument><argument>vpn-connect-nit-gateway-N</argument><argument>user@company.com</argument><argument>GP-DUO-AUTH</argument><argument>vsys1</argument><argument>%28empty_domain%29</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>-1</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument><argument></argument><argument>4</argument><argument>unknown</argument><argument></argument></application-desc></jnlp>
2023-05-17 16:18:16.382 INFO  [59437] [GPClient::onGatewaySuccess@385] Gateway login succeeded, got the cookie xxx
2023-05-17 16:18:16.431 INFO  [59437] [GPClient::onVPNLogAvailable@518] Output of `openconnect --version`: OpenConnect version v9.01
Using GnuTLS 3.8.0. Features present: TPM, TPMv2, PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /etc/vpnc/vpnc-script

2023-05-17 16:18:16.431 INFO  [59437] [GPClient::onVPNLogAvailable@518] Got extra OpenConnect args for server: vpn.company.com, <empty>
2023-05-17 16:18:16.431 INFO  [59437] [GPClient::onVPNLogAvailable@518] Start process with arugments: --protocol=gp, -u, , --cookie-on-stdin, vpn.company.com
2023-05-17 16:18:16.432 INFO  [59437] [GPClient::onVPNLogAvailable@518] Openconnect started successfully, PID=59625
2023-05-17 16:18:16.446 INFO  [59437] [GPClient::onVPNLogAvailable@518] POST https://vpn.company.com/ssl-vpn/getconfig.esp

2023-05-17 16:18:16.463 INFO  [59437] [GPClient::onVPNLogAvailable@518] Connected to xxx

2023-05-17 16:18:16.550 INFO  [59437] [GPClient::onVPNLogAvailable@518] SSL negotiation with vpn.company.com

2023-05-17 16:18:16.595 INFO  [59437] [GPClient::onVPNLogAvailable@518] Connected to HTTPS on vpn.company.com with ciphersuite (TLS1.2)-(RSA)-(AES-256-GCM)

2023-05-17 16:18:16.618 INFO  [59437] [GPClient::onVPNLogAvailable@518] Matching client config not found
Creating SSL connection failed
Unknown error; exiting.
```

**Comment by yuezk** [comment] 2023-05-18 01:12
The WebSocket is used to communicate with the browser devtools to intercept the response to retrieve the authentication cookie. You could retry or check if an update is available for `qt5-qtwebengine-devel` and `qt5-qtwebsockets-devel`.

**Comment by risostk** [comment] 2023-05-20 19:22
Thank you! The two packages are already up-to-date. The tool used to work without any issue. Maybe the issue is related to a new version of qt? My current version is
qt5-qtwebengine-devel-5.15.12-5
qt5-qtwebsockets-devel-5.15.9-1

**Comment by andisan86** [comment] 2023-10-04 15:38
@yuezk 

I got something similar error. Not sure if it has the same root cause though.
OS: Mint 21.1
gpclient: 1.4.9

```
2023-10-04 22:32:06.791 INFO  [6981] [SAMLLoginWindow::checkSamlResult@80] Checking the authentication result...
2023-10-04 22:32:06.791 INFO  [6981] [SAMLLoginWindow::checkSamlResult@97] Got the SAML authentication information successfully. username: ******, preloginCookie: ****** 
2023-10-04 22:32:06.791 INFO  [6981] [PortalAuthenticator::onSAMLLoginSuccess@142] SAML login succeeded, got the prelogin-cookie
2023-10-04 22:32:06.791 INFO  [6981] [PortalAuthenticator::fetchConfig@173] Fetching the portal config from https://vpn.****.com/global-protect/getconfig.esp
2023-10-04 22:32:06.814 ERROR [6981] [CDPCommandManager::onSocketError@86] WebSocket error1
2023-10-04 22:32:06.814 INFO  [6981] [CDPCommandManager::onSocketDisconnected@81] WebSocket disconnected
```

Those two packages you mentioned did not exist though. Is there another way to check what could be the issue?

**Comment by martindorey** [comment] 2023-12-29 17:11
> ... the UI is stuck on Authenticating...
...
> 2023-10-04 22:32:06.814 ERROR [6981] [CDPCommandManager::onSocketError@86] WebSocket error1
> 2023-10-04 22:32:06.814 INFO  [6981] [CDPCommandManager::onSocketDisconnected@81] WebSocket disconnected

Perhaps more like https://github.com/yuezk/GlobalProtect-openconnect/issues/252.

**Comment by yuezk** [comment] 2024-01-25 12:56
This should be fixed in 2.x, the authentication workflow is more robust now and doesn't rely on websocket.

**Closed by yuezk** 2024-01-25 12:56 UTC
