### ISSUE TITLE
automatically disconnect connection, when system goes to suspend 

### ISSUE THREAD

**Issue by orclex** [yuezk/GlobalProtect-openconnect#429] opened 2024-09-26 07:55 UTC
When a globalprotect-openconnect connection is open and my notebook enters suspend mode, the network connection is broken after wake up from suspend.
The VPN connection is lost, but settings like DNS are still set. globalprotect-openconnect tries to reconnect, but cannot find the previously set DNS server and hangs. I only can restart the NetworkManager.

If globalprotect-openconnect could hook into the suspend scripts and run a disconnect before going to sleep, I guess the problem should be fixed.

**Environment:**
 - OS: [Ubuntu 24.04.1]
 - Desktop Environment: [KDE]
 - Is remote SSH? [No]
- globalprotect-openconnect:  2.3.4-ppa1~ubuntu23.10

**Comment by h4cking4fun** [comment] 2024-10-01 05:58
Yes, this is a known issue tracked by #267. But I couldn't reproduce myself. I have investigated using the `systemd` service to hook into the suspend event and disconnect the VPN. Looks worked, but I'm not very confident about that.

Closing this and using that one to track.

**Comment by yuezk** [comment] 2024-10-01 05:59
Yes, this is a known issue tracked by https://github.com/yuezk/GlobalProtect-openconnect/issues/267. But I couldn't reproduce myself. I have investigated using the systemd service to hook into the suspend event and disconnect the VPN. Looks worked, but I'm not very confident about that.

Closing this and using that one to track.

**Closed by yuezk** 2024-10-01 05:59 UTC
