### ISSUE TITLE
how to downgrade pre 2.0?

### ISSUE THREAD

**Issue by nerdCopter** [yuezk/GlobalProtect-openconnect#290] opened 2024-01-20 15:59 UTC
how to downgrade to 1.x? binaries not available via github nor repo. 
2.0 not connecting, locked out of employer VPN.
`Ubuntu 22.04.3 LTS`

**Comment by tzhao42** [comment] 2024-01-20 16:03
Just curious, what's the output of `gpclient`? I'm wondering if it's the same issue a few of us have been having (#289 #286)

**Comment by nerdCopter** [comment] 2024-01-20 16:10
```
$ gpclient connect [redacted
[2024-01-20T16:09:06Z INFO  gpclient::cli] gpclient started: 2.0.0-beta2 (2024-01-18)
[2024-01-20T16:09:06Z INFO  gpapi::portal::prelogin] Portal prelogin, user_agent: PAN GlobalProtect
[2024-01-20T16:09:07Z INFO  gpauth::cli] gpauth started: 2.0.0-beta2 (2024-01-18)
[2024-01-20T16:09:07Z INFO  gpauth::auth_window] Open auth window, user_agent: PAN GlobalProtect
[2024-01-20T16:09:07Z INFO  gpauth::auth_window] Auth window user agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
[2024-01-20T16:09:07Z INFO  gpauth::auth_window] Load the SAML request as URI...
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Loaded uri: https://l**********m/32bd7351-5013-47fc-8f57-e34743b3aa75/saml2?SAMLRequest=j**********E&RelayState=y**********%3D
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Raise window cancelled
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Loaded uri: https://d**********u/SAML20/SP/ACS
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:09:08Z INFO  gpauth::auth_window] Got auth data from headers
[2024-01-20T16:09:08Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect

Error: Invalid auth cookie, retrying can help
```

**Comment by nerdCopter** [comment] 2024-01-20 16:45
side note: resolved with _official_ paloalto globalprotect client which had never worked well in the past.  `6.1.3.0-703`. install script was _required_, as direct `dpkg -i` of the `.deb` did not connect.

**Comment by sh4t7er** [comment] 2024-01-20 20:29
> how to downgrade to 1.x? binaries not available via github nor repo. 2.0 not connecting, locked out of employer VPN. `Ubuntu 22.04.3 LTS`

@nerdCopter   https://github.com/yuezk/GlobalProtect-openconnect/issues/280#issuecomment-1897922829

**Comment by obfuscated** [comment] 2024-01-23 10:52
@yuezk Would it be possible to restore the last stable binary packages until the 2.0 release is out of beta and it is known to be working for most people? I'm locked out of vpn on a Rocky 8 using beta6 and I don't know what to do. 1.4 worked fine.

**Comment by obfuscated** [comment] 2024-01-23 11:01
@yuezk Ah, so the 0.2mb package is actually working :shock: So what a regression in size and capabilities :)

**Comment by jvalecillos** [comment] 2024-01-23 14:19
This is what I had to do in Ubuntu `22.04` (I was using the deb from the PPA repo), since 2.0 stop working (also it is not clear if the app is open source anymore):

```bash
sudo apt-get remove globalprotect-openconnect
git clone --depth=1 --branch 1.x https://github.com/yuezk/GlobalProtect-openconnect.git
cd GlobalProtect-openconnect/
./scripts/install-ubuntu.sh
```

That will install the previous working version.

**Comment by yuezk** [comment] 2024-01-24 01:15
> @yuezk Ah, so the 0.2mb package is actually working :shock: So what a regression in size and capabilities :)

The breaking change has been fixed since 2.0.0-beta7. 

- Rust by default uses static linking, by compressing most of its dependencies in the binary, so the size becomes bigger, I will try to reduce the binary size, but not the highest priority.
- The authentication workflow now is aligned with the old version and is more robust, which also supports external browser authentication. Good for Yubikey users.

Others who want sticky to 1.4.9 can follow the instructions in this issue or the instructions in https://github.com/yuezk/GlobalProtect-openconnect/tree/1.x, both are the same.

Closing.

**Closed by yuezk** 2024-01-24 01:15 UTC

**Comment by ttppss** [comment] 2024-02-15 15:14
Can someone help me with this issue when trying to downgrade from 2.0.0 to 1.4.9 with ./scripts/install-ubuntu.sh on ubuntu 20.04? Thanks!

[sudo] password for user: 
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                   
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease                    
Hit:4 https://deb.nodesource.com/node_21.x nodistro InRelease                       
Hit:5 https://dl.google.com/linux/chrome/deb stable InRelease                       
Hit:6 http://ppa.launchpad.net/dwmw2/openconnect/ubuntu focal InRelease    
Hit:7 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease
Hit:8 http://ppa.launchpad.net/yuezk/globalprotect-openconnect/ubuntu focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5websockets5-dev is already the newest version (5.12.8-0ubuntu1).
qt5keychain-dev is already the newest version (0.10.0-1build1).
qttools5-dev is already the newest version (5.12.8-0ubuntu1).
build-essential is already the newest version (12.8ubuntu1.1).
qtbase5-dev is already the newest version (5.12.8+dfsg-0ubuntu2.1).
qtwebengine5-dev is already the newest version (5.12.8+dfsg-0ubuntu1.1).
openconnect is already the newest version (9.12-0-focal1).
The following packages were automatically installed and are no longer required:
  libayatana-appindicator3-1 libayatana-indicator3-7
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
-- CMAKE_INSTALL_PREFIX was set to: /usr
-- CMAKE_LOGNAME: user
-- Found third party locally for SingleApplication
-- Found third party locally for SingleApplication
-- Found third party locally for plog
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/globalprotect-openconnect-1.4.9/build
[  1%] Automatic MOC and UIC for target QtSignals
[  2%] Automatic MOC and UIC for target inih
[ 13%] Built target SingleApplication-GPService
[ 25%] Built target SingleApplication-GPClient
[ 36%] Built target plog-GPClient
[ 36%] Built target QtSignals_autogen
[ 36%] Built target inih_autogen
Consolidate compiler generated dependencies of target QtSignals
Consolidate compiler generated dependencies of target inih
[ 41%] Built target inih
[ 45%] Built target QtSignals
[ 47%] Automatic MOC and UIC for target gpservice
[ 50%] Built target gpservice_autogen
Consolidate compiler generated dependencies of target gpservice
[ 61%] Built target gpservice
[ 62%] Automatic MOC and UIC for target gpclient
[ 63%] Built target gpclient_autogen
Consolidate compiler generated dependencies of target gpclient
[ 65%] Linking CXX executable gpclient
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libqt5keychain.so.0.10.0: undefined reference to `qt_version_tag@Qt_5.12'
collect2: error: ld returned 1 exit status
make[2]: *** [GPClient/CMakeFiles/gpclient.dir/build.make:475: GPClient/gpclient] Error 1
make[1]: *** [CMakeFiles/Makefile2:353: GPClient/CMakeFiles/gpclient.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by FlockOfBird** [comment] 2024-02-27 03:22
Hi, I am trying to downgrading to version 1 following @jvalecillos commands but I face this error. Can you please guide me regarding the issue?

Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 http://apt.pop-os.org/proprietary jammy InRelease                                                       
Hit:3 http://apt.pop-os.org/release jammy InRelease                                                           
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease                     
Hit:5 http://apt.pop-os.org/ubuntu jammy InRelease                               
Hit:6 http://apt.pop-os.org/ubuntu jammy-security InRelease                      
Hit:7 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/dwmw2/openconnect/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/elementary-os/daily/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/lutris-team/lutris/ubuntu jammy InRelease
Ign:13 https://ppa.launchpadcontent.net/marlin-devs/marlin-daily/ubuntu jammy InRelease
Ign:14 https://ppa.launchpadcontent.net/mc3man/xerus-media/ubuntu jammy InRelease
Hit:15 https://ppa.launchpadcontent.net/umang/indicator-stickynotes/ubuntu jammy InRelease
Hit:16 https://ppa.launchpadcontent.net/yuezk/globalprotect-openconnect/ubuntu jammy InRelease
Err:17 https://ppa.launchpadcontent.net/marlin-devs/marlin-daily/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.80 443]
Err:18 https://ppa.launchpadcontent.net/mc3man/xerus-media/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/marlin-devs/marlin-daily/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/mc3man/xerus-media/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
