### ISSUE TITLE
Trying to Build in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ndunn990** [yuezk/GlobalProtect-openconnect#4] opened 2020-03-18 02:32 UTC
I realize I'm probably something of an odd ball, here. I apologize for being weird. I'm running openSUSE Tumbleweed, version 20200314.

I've been trying to build GlobalProtect-openconnect, and I'm pretty certain I have all necessary dependencies. However, when I try to run make, I run into something of a perplexing error.

![screenshot_2020-03-17_22-28-18_811173376](https://user-images.githubusercontent.com/20825134/76919232-ade7ea00-689e-11ea-9433-2aa91094f685.png)

Again, I _believe_  I have the necessary dependencies installed. I think the 'devel_qt5' pattern includes all necessary packages.

![screenshot_2020-03-17_22-29-49_158440300](https://user-images.githubusercontent.com/20825134/76919286-d839a780-689e-11ea-8906-685319a26229.png)

I'm just looking for a decent starting point as I seem unable to figure out what might be wrong. I'm willing to do a bit of leg work if someone can get me started, at least.

**Comment by yuezk** [comment] 2020-03-18 13:46
I see and I will take a look at openSUSE later.

**Comment by yuezk** [comment] 2020-03-18 14:34
And which desktop environment do you use? KDE, GNOME or somehting else?

**Comment by ndunn990** [comment] 2020-03-18 17:05
I have two DEs in place. One is GNOME and the other is Sway (i3 for Wayland, essentially). Like I said, I'm an oddball. If I can get it running in GNOME, I can probably go from there to make it work in Sway.

**Comment by yuezk** [comment] 2020-03-22 04:46
@ndunn990 I didn't run into your problem in the fresh installed openSUSE Tumbleweed 20200314 in VirtualBox.

Steps to build
```bash
sudo zypper install libqt5-qtbase-devel libqt5-qtwebsockets-devel libqt5-qtwebengine-devel
cd GlobalProtect-openconnect
qmake-qt5 CONFIG+=release
make
```

Below are the output of `make`
```text
kevin@10:~/GlobalProtect-openconnect> make
cd GPClient/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /home/kevin/GlobalProtect-openconnect/GPClient/GPClient.pro CONFIG+=release ) && make -f Makefile 
make[1]: Entering directory '/home/kevin/GlobalProtect-openconnect/GPClient'
```
`qmake-qt5` version

```
kevin@10:~/GlobalProtect-openconnect> qmake-qt5 --version
QMake version 3.1
Using Qt version 5.14.1 in /usr/lib64
```
I don't know why your run into this problem. But could you please repeat the steps above and try again?

**Comment by yuezk** [comment] 2020-05-23 10:09
Closing this as I couldn't reproduce it.

**Closed by yuezk** 2020-05-23 10:09 UTC
