### ISSUE TITLE
Authorization fails if selectedGateway config is present

### ISSUE THREAD

**Issue by tinkermakar** [yuezk/GlobalProtect-openconnect#147] opened 2022-05-07 17:22 UTC
The VPN server supports a list of gateways around the world. It also has a HIP chek in place.

Everything is fine when I connect for the first time, but if I try to reconnect (or connect after a reboot) I get a `403 Not Assigned` Octa error and fail to reconnect.

I have a weird workaround -- everything works again once I delete the line with `selectedGateway` in this file: `~/.config/com.yuezk.qt/GPClient.conf`

**Comment by yuezk** [comment] 2022-06-12 13:22
Can you upgrade it to the latest version to see if it is reproducible? Thanks.

**Comment by Vikingtons** [comment] 2022-09-03 12:15
I have a somewhat similar issue related to that property. It seems I'm unable to switch gateways using the UI / status bar notification icon. I have to modify the selectedGateway property to my desired gateway to be able to connect to it.

**Comment by Vikingtons** [comment] 2022-09-03 12:24
I have a similar vpn server setup to makar2

I'm now unable to connect to any other gateway except from the top one in the list.

After manually changing selectedGateway property to my desired city in GPClient.conf, I was able to successfully auth with my local gateway (thank you for the heads up).

This isn't a reliable method to connect to my local gateway, however. I haven't managed to get this to work a second time.

**Comment by makar2** [comment] 2022-10-24 00:47
> Can you upgrade it to the latest version to see if it is reproducible? Thanks.

Soory, just saw your reply -- the issue is still present on v1.4.8

**Comment by nekodojo** [comment] 2022-11-04 19:45
I had the same issue. Worked great the first time. Second time, tried to reconnect to same gateway and got red "Cannot complete at this time" message on the first screen.  Removing ~/.config/com.yuezk.qt/ allowed me to connect again.   version: 1.4.8

**Comment by yuezk** [comment] 2024-03-23 13:38
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.

**Closed by yuezk** 2024-03-23 13:38 UTC
