### ISSUE TITLE
Docker image [help wanted]

### ISSUE THREAD

**Issue by thatnerdjosh** [yuezk/GlobalProtect-openconnect#41] opened 2020-12-25 13:55 UTC
https://github.com/thatnerdjosh/GlobalProtect-openconnect/blob/feature/js-add_dockerfile/Dockerfile

I started working on a docker image for this client... and got it mostly working, except it crashes once it tries to redirect to the login page with this error:

```
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
```

I am not an experienced QT (or C++ for that matter) developer... so I am quite stuck figuring this one out. I am guessing it has something to do with opengl support inside the container

**Comment by thatnerdjosh** [comment] 2020-12-25 14:56
Seems to not only be a docker issue https://github.com/yuezk/GlobalProtect-openconnect/issues/36

**Comment by thatnerdjosh** [comment] 2020-12-25 16:46
So I managed to fix it using this: https://github.com/gasparka/qttest/blob/master/Dockerfile#L14

But I don't understand why that fixed it

**Comment by yuezk** [comment] 2020-12-28 03:07
Not sure about the root cause of this issue either. But glad you got this issue solved. I'm closing this and welcome your feedback if you have any other questions.

**Closed by yuezk** 2020-12-28 03:07 UTC
